### ISSUE TITLE
[ENG] Missing flutter doctor --android-licenses command

### ISSUE THREAD

**Issue by Ajju-kld** [shan-shaji/flutter-prep#1]
## great work brother  😇
I was searching for the same for referring it to use it in ubuntu for college purpose. it help me out here thanks
But by reviewing the code, there found something missing. I think you have forgot to add command to accept Android Sdk license.
```flutter doctor --android-licenses```
adding this to the code will make it somewhat complete.

**Comment by shan-shaji** [comment]
Thanks @Ajju-kld, If you would like contribute feel free to make a PR and If you feel this is useful please support by starring the repo.

**Comment by shan-shaji** [comment]
Hello @Ajju-kld, please inform me whether you are currently working on this issue or not.

**Comment by Ajju-kld** [comment]
currently i am not working on the issue. its just adding one line that can be done self.
