### ISSUE TITLE
I don't understand how I can benefit from it ?

### ISSUE THREAD

**Issue by azabcodes** [shan-shaji/flutter-prep#2]
just write this in terminal ?

curl -fsSl https://raw.githubusercontent.com/shan-shaji/setup-flutter/main/setup-flutter | /bin/bash

and all about flutter will installed

**Comment by shan-shaji** [comment]
@mazab99 To clarify, the script will handle the installation of fvm and set up the path for you, so you don't need to worry about the 'fvm not found error' or configuring fvm flutter path. Additionally, it can install Android Studio or VS Code for you, but it won't set up any other configurations needed to work with Flutter. I am planning to add that in future but currently it does not have the support. Installation of xcode, android simulator setup should be done manually now. I created this script to simplify setting up Flutter on multiple devices, as I was tired of manually configuring everything. 


I hope you have got the point. Thank you for opening this issue.

**Comment by azabcodes** [comment]
OK,  can you make video for how to use this ?

**Comment by shan-shaji** [comment]
Sure would love to but i am not sure when will i be able to make it. You just need to run that one line @mazab99  to setup.

**Comment by shan-shaji** [comment]
@mazab99 this will only work on mac/linux. And i was only able to test it on ubuntu.

**Comment by azabcodes** [comment]
OK  , at least write the steps or an explanation for using

**Comment by shan-shaji** [comment]
@mazab99  Yup will update the necessary steps tomorrow.

**Comment by azabcodes** [comment]
Thanks bro

**Comment by shan-shaji** [comment]
Hey @mazab99 , I have updated the docs.

**Comment by shan-shaji** [comment]
Hey @mazab99 , Feel free to let me know if anything needs to be added. Feel free to close this issue if the details provided are enough.

**Comment by azabcodes** [comment]
now this is so good ( thanks bro )

**Comment by shan-shaji** [comment]
Closing this issue for now. @mazab99 Feel free to re-open the issue if there is anything that needs to be added on the README.md.
